{"name": "test_sign_up_negative_password_mismatch", "status": "broken", "statusDetails": {"message": "TypeError: find_element() takes from 1 to 3 positional arguments but 13 were given", "trace": "app = <application.Application object at 0x038C6B90>\nmake_screen = <function make_screen at 0x0367D078>\n\n    @allure.feature('Sign up')\n    @allure.story('Sign up negative')\n    def test_sign_up_negative_password_mismatch(app, make_screen):\n        \"\"\" Testcase for sign up user.\n        Negative. Using differen password and matching password \"\"\"\n        app.header.click_icon()\n>       app.header.click_log_in()\n\ntest_sign_up.py:99: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\pages\\header.py:31: in click_log_in\n    self.browser.click_element_by_text_simple(self.locators.LOG_IN)\n..\\driver_wrapper.py:53: in click_element_by_text_simple\n    WebDriverWait(self.driver, self.default_timeout).until(EC.element_to_be_clickable(locator_and_text[0]))\nC:\\Users\\Nataliya\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py:71: in until\n    value = method(self._driver)\nC:\\Users\\Nataliya\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py:297: in __call__\n    element = visibility_of_element_located(self.locator)(driver)\nC:\\Users\\Nataliya\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py:128: in __call__\n    return _element_if_visible(_find_element(driver, self.locator))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\ndriver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"278494625e35f575792980cdda014113\")>\nby = 'css selector'\n\n    def _find_element(driver, by):\n        \"\"\"Looks up an element. Logs and re-raises ``WebDriverException``\n        if thrown.\"\"\"\n        try:\n>           return driver.find_element(*by)\nE           TypeError: find_element() takes from 1 to 3 positional arguments but 13 were given\n\nC:\\Users\\Nataliya\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py:411: TypeError"}, "description": " Testcase for sign up user.\n    Negative. Using differen password and matching password ", "start": 1566416675922, "stop": 1566416676147, "uuid": "9919b5c6-181a-434a-9929-080f47d89829", "historyId": "760b606ef92b5dc3bd7f949503775c72", "fullName": "tests.test_sign_up#test_sign_up_negative_password_mismatch", "labels": [{"name": "feature", "value": "Sign up"}, {"name": "story", "value": "Sign up negative"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_sign_up"}, {"name": "subSuite"}, {"name": "host", "value": "DESKTOP-Q2AH420"}, {"name": "thread", "value": "6428-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_sign_up"}]}